name: CI

on:
    push:
        branches:
            - master
    pull_request:

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
                node: [10.x, 12.x, 14.x]
            fail-fast: false

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Set node version to ${{ matrix.node }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node }}

            - name: Versions
              run: yarn versions

            - name: Install dependencies
              run: yarn install --frozen-lockfile

            - name: Check outdated dependencies
              run: yarn outdated

            - name: Lint
              run: yarn lint

            - name: Test
              run: yarn jest --ci --silent --reporters=default --reporters=jest-junit

            - name: Upload test artifact
              uses: actions/upload-artifact@v2
              if: ${{ always() }}
              with:
                  name: JUnit_${{ matrix.os }}_${{ matrix.node }}_${{ github.sha }}
                  path: junit.xml

            # - name: Audit dependencies
            #   run: yarn audit --groups dependencies

            - name: Build
              run: yarn build
